FROM python:3.13-slim

LABEL org.opencontainers.image.source="https://github.com/CodyCBakerPhD/historia"
LABEL org.opencontainers.image.description="A Docker image of the latest released version of Historia."

RUN pip install --no-cache-dir nwb2bids

ENTRYPOINT ["historia"]
CMD ["--help"]
