FROM python:3.13-slim

LABEL org.opencontainers.image.source="https://github.com/CodyCBakerPhD/historia"
LABEL org.opencontainers.image.description="A Docker image of the latest released version of historia."

WORKDIR /opt/historia

COPY LICENSE.txt README.md pyproject.toml ./
COPY src ./src

RUN python -m pip install --upgrade pip \
    && python -m pip install --no-cache-dir .

ENTRYPOINT ["historia"]
CMD ["--help"]
