name: Daily tests

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  DailyTests:
    permissions:
      contents: read
    uses: ./.github/workflows/testing.yml
    secrets: inherit
